In [1]:
n,m = rating_mat.shape
d = 20
U = np.random.randint(10, size=(n, d))
V = np.random.randint(10, size=(m, d))

NameError: name 'rating_mat' is not defined

In [639]:
U.astype(float)
V.astype(float)
y_hat=U@V.T
y_hat.shape

(943, 1682)

In [641]:
y=rating_mat.values
y.shape

(943, 1682)

In [643]:
def costU(V):
    return costU
def costVT(U):
    return costV

In [2]:
def gradient_descent(U, V, learn_rate=0.0001,n_iter=100, lamda=10):
    for _ in range(n_iter):
        y_hat = U@V.T
        costU= -np.matmul((y-y_hat),V) + lamda*U
        costV= -np.matmul((y-y_hat).transpose(),U) + lamda*V

        U=U-learn_rate*costU
        V=V-learn_rate*costV
        
        print(np.sum((y-U@V.T)**2) + lamda*(np.linalg.norm(U, ord='fro') + np.linalg.norm(V, ord='fro')))
    return U,V

In [3]:
U@V.T

NameError: name 'U' is not defined

In [33]:
import pandas as pd
import numpy as np
from numpy import linalg as LA
import random 
from sklearn.metrics import precision_score, recall_score

In [34]:
def train_test_split(data, ratio=0.3):
    train_data = data.copy()
    nonzero_row, nonzero_col = np.where(data != 0)
    nonzero_list = list(zip(nonzero_row, nonzero_col))
    train_list = random.sample(nonzero_list, int(len(nonzero_list)*ratio))
    nonzerorow_train, nonzerocol_train= zip(*train_list)
    train_data[nonzerorow_train, nonzerocol_train] = 0
    test_data = data - train_data
    return train_data, test_data

In [35]:
def gradient(y,U, V, mask, lamda, alpha):
    for i in range(100):
        
            yhat = U @ V.T
            error = (y - yhat) * mask
            loss = (np.sum(error**2) + lamda * (np.linalg.norm(U, 'fro')**2 + np.linalg.norm(V, 'fro')**2)) / 2
            dU = -error @ V + lamda * U
            dV = -error.T @ U + lamda * V
            U = U - alpha * dU
            V = V - alpha * dV
        
            # print(f"Iteration {i+1}, Loss: {loss}")
    return U,V

In [41]:
def mean_abs_error(y_test,prediction):
    mask=(y_test>0).astype(float)
    
    MAE = np.sum(np.abs((y_test-pred)*(y_test>0)))/np.sum(y_test>0)
    return MAE
    
    

In [42]:
def training(y,lamda=8.5,alpha=0.00001):
    mask = (y > 0).astype(float)
   # print(mask,y.shape)
    n,m = y.shape
    d = 100
    U = np.random.rand(n, d)
    V = np.random.rand(m, d)
    U,V = gradient(y,U,V,mask,lamda,alpha=alpha)
    return U, V
    
def prediction(U, V):    
    yhat = U@V.T
    yhat[yhat>5] = 5
    yhat[yhat<1] = 1
    # yhat=np.round(yhat)
    return yhat

In [45]:
#from sklearn.model_selection import train_test_split

data = pd.read_csv('C:/Users/VK/Downloads/ml-100k/ml-100k/u.data', header=None,sep='\t')
data = data.reindex(sorted(data.columns), axis=1)
data.columns=["user","items","rating","time_stamp"]
rating_mat = pd.pivot_table(data,index='user',columns='items',values='rating')
rating_mat.fillna(0,inplace=True)
# split
y_train, y_test = train_test_split(rating_mat.values)
U_train,V_train=training(y_train,8.5,0.0001)
pred = prediction(U_train, V_train)
print(mean_abs_error(y_test,pred))
classification(y_train,pred)

1.176009275351064
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 

 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.6290597533706745 0.733132079366308


In [39]:
def classification(data,pred):
    mask=(data>0).astype(float)
    y_class=data.copy()*mask 
    pred=pred*mask
    pred_class=(pred>3).astype(int) 
    y_class=(y_class>3).astype(int) 
    print(y_class,"\n\n", pred_class  )
    precision=precision_score(y_class,pred_class,average='micro') 
    recall=recall_score(y_class,pred_class,average='micro')
    print(precision,recall)

In [31]:
thresold = 3
K = 10
mask = (y_train > 0).astype(float)
y_pred = ((pred * mask) > thresold).astype(int)
print(y_actual)
y_actual_sort = np.fliplr(np.sort(y_actual))
print(y_actual_sort)
topK=y_actual_sort[:K]
relevant_top_k=topK.sum()
print(relevant_top_k)
precision_at_k=relevant_top_k/K
print(f"Precision@{K}:{precision_at_k}")
# mask=(y10_shape>0).astype(float)
# y10_shape=((y10_shape * mask) > thresold).astype(int)
# y10_shape
# pred10_shape=pred[:10]

# # mask=(pred10_shape>0).astype(float)
# pred10_shape=((pred10_shape * mask) > 3).astype(int)
# preci_10=precision_score(y10_shape,pred10_shape,average='micro')
# print(preci_10)

NameError: name 'y_actual' is not defined