In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X, Y = load_diabetes(return_X_y = True)

In [7]:
def DataShuffle(X_data, Y_data):
    data_num = np.arange(X_data.shape[0])
    np.random.shuffle(data_num)
    return X_data[data_num], Y_data[data_num]

In [8]:
def train_tst_split(X_data,Y_data,ratio=0.3, shuffle=True):
    if shuffle:
        X_data, Y_data = DataShuffle(X_data, Y_data)
    if ratio < 1:
        test_size = len(Y_data) - int(len(Y_data) * ratio)
        X_train, X_test = X_data[:test_size], X_data[test_size:]
        Y_train, Y_test = Y_data[:test_size], Y_data[test_size:]
    return X_train, X_test, Y_train, Y_test

In [25]:
class Multi_regression:
    def __init__(self):
        self.m = None
        self.b = None
    def fit_line(self, x_train, y_train, alpha = 0.1):
        x_train = np.insert(x_train, 0, 1, axis=1)
        weight = np.linalg.inv(x_train.T @ x_train)@(x_train.T)@ y_train
        self.b = weight[0]
        self.m = weight[1:]
        return self.m, self.b
    def predict(self, x_test):
        y_pred = np.dot(x_test, self.m) + self.b
        return y_pred

In [27]:
x_train, x_test, y_train, y_test = train_tst_split(X, Y)
ml = Multi_regression()
print(ml.fit_line(x_train, y_train))
ml.predict(x_test)

(array([ -29.00298318, -258.49779591,  511.28409372,  318.78187144,
       -662.59562364,  211.91810928,  128.5955284 ,  285.28837811,
        706.75688322,   99.5816405 ]), 150.72931449444195)


array([121.88810647, 113.49014496, 237.88694156, 121.87569418,
       137.5981235 , 104.51991811, 131.63326285,  86.79160974,
       188.64181713,  67.17322879, 117.03174971, 115.10560886,
       189.47177282, 234.49841444, 105.79798697, 143.50981661,
       109.86909957,  68.76270434,  63.4031408 , 168.47956267,
       150.08641041, 136.80510806, 253.62376085, 119.91365123,
       118.50286701, 222.6557531 ,  52.94966411, 185.37580202,
       262.36774223, 202.15881218, 130.61573631, 172.43313235,
        41.7127357 , 158.869438  , 206.06253686,  89.97206011,
        89.02973147, 155.96105789,  93.31436627, 149.61885425,
       150.7293127 ,  89.90469646, 144.25602226,  86.20051359,
       208.72313775, 127.15374291,  59.70263426, 255.64743618,
       150.93462882,  80.94021307,  93.71294381, 290.79441279,
        87.53903741,  80.24213665,  59.10953507, 217.43524964,
       231.58477207,  96.20228108, 174.82637921, 110.4607766 ,
       147.20965082, 191.71961744,  72.43080104, 214.38

In [19]:
x_train = np.insert(x_train, 0, 1, axis=1)
weight = np.ones(x_train.shape[0])
x_train[0]

array([ 1.        ,  1.        ,  1.        ,  0.04170844, -0.04464164,
       -0.00728377,  0.02875809, -0.04284755, -0.04828615,  0.05232174,
       -0.0763945 , -0.07213275,  0.02377494])

In [28]:
!nvidia-smi

Tue Jul 22 15:27:07 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.41       Driver Version: 527.41       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1000       WDDM  | 00000000:01:00.0  On |                  N/A |
| 35%   51C    P0    N/A /  50W |   1256MiB /  4096MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------