In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


In [2]:
!nvidia-smi

Thu Jul 24 16:30:05 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.41       Driver Version: 527.41       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1000       WDDM  | 00000000:01:00.0  On |                  N/A |
| 35%   48C    P8    N/A /  50W |    562MiB /  4096MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [6]:
vector.ndim

1

In [7]:
matrix = torch.tensor([[7,2],
                       [3,5]])
print(f"matrix shape {matrix.shape} and matrix dimension is {matrix.ndim}")

matrix shape torch.Size([2, 2]) and matrix dimension is 2


In [8]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]]])
print(f"TENSOR shape {TENSOR.shape} and TENSOR dimension is {TENSOR.ndim}")

TENSOR shape torch.Size([1, 3, 4]) and TENSOR dimension is 3


### Random Tensor 

##### Random Tensor Understanding : https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [9]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9536, 0.6154, 0.8819, 0.5300],
        [0.1665, 0.3102, 0.1191, 0.0966],
        [0.8724, 0.3802, 0.9949, 0.1582]])

In [10]:
print(f"Random Tensor shape {random_tensor.shape} and Random Tensor dimension is {random_tensor.ndim}")

Random Tensor shape torch.Size([3, 4]) and Random Tensor dimension is 2


In [11]:
#Create a random Tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [12]:
#Create all Zeros Tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#create all Ones Tesnsor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Creating a range of Tensor and Tensor-like

In [14]:
# use torch.range()
one_to_ten = torch.arange(1,11)
# using step in arange
one_to_some_step = torch.arange(start = 1, end = 11, step = 1)
one_to_some_step


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Create Tensor-like
ten_zeros = torch.zeros_like(input=one_to_some_step)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataType
#### **NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
     1.Tensor not right shape    
     2.Tensor not right dataType
     3.Tensor not on the right Device


In [16]:
float_32_tensor = torch.tensor([3.0, 6.0, 7.0], 
                               dtype=None, # what data type is the tensor (e.g. float32 and float 16)
                               device=None,# what device  is your tensor on
                               requires_grad=False) # Wheather or not to track gradient with this tensors operation
float_32_tensor

tensor([3., 6., 7.])

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 7.], dtype=torch.float16)

In [18]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 49.])

In [19]:
# Create some Tensor 

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2068, 0.1336, 0.2142, 0.6355],
        [0.2521, 0.3705, 0.8063, 0.8249],
        [0.0068, 0.0710, 0.6955, 0.7321]])

In [20]:
# Find Out Detalis about Some_Tensor 
print(f"Datatype of Tensor is {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

Datatype of Tensor is torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on cpu


### Manipulating the Tensor (Tensor operation)


In [21]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [22]:
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
# Manipulating using Functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [23]:
#Element wise Multiplication
print(tensor,"*",tensor)
print(f"Equal to: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal to: tensor([1, 4, 9])


In [24]:
%%time
# Matrix Multiplication 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 2 ms


tensor(14)

In [25]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [26]:
print(torch.matmul(torch.rand(3,2), (torch.rand(3,2)).T))
torch.mm(torch.rand(2,3), (torch.rand(2,3)).T) # torch.mm is same as torch.matmul (it's an alias for matmul)

tensor([[0.3300, 0.0447, 0.3671],
        [0.2450, 0.0238, 0.3181],
        [0.3555, 0.0529, 0.3723]])


tensor([[0.6507, 0.5103],
        [0.7139, 0.5445]])

#### Finding The min, Max, Mean,  Sum, Etc (tensor aggregation) 

In [27]:
x = torch.arange(start = 0, end= 100, step= 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
f"min :{x.min()} and {torch.min(x)}", f"max: {x.max()} and {torch.max(x)}"

('min :0 and 0', 'max: 90 and 90')

In [37]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))