In [9]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


In [10]:
!nvidia-smi

Thu Jul 24 17:39:31 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.41       Driver Version: 527.41       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1000       WDDM  | 00000000:01:00.0  On |                  N/A |
| 36%   48C    P8    N/A /  50W |    626MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensor

In [11]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.item()

7

In [13]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [14]:
vector.ndim

1

In [15]:
matrix = torch.tensor([[7,2],
                       [3,5]])
print(f"matrix shape {matrix.shape} and matrix dimension is {matrix.ndim}")

matrix shape torch.Size([2, 2]) and matrix dimension is 2


In [16]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]]])
print(f"TENSOR shape {TENSOR.shape} and TENSOR dimension is {TENSOR.ndim}")

TENSOR shape torch.Size([1, 3, 4]) and TENSOR dimension is 3


### Random Tensor 

##### Random Tensor Understanding : https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8256, 0.5529, 0.6824, 0.7014],
        [0.8647, 0.3458, 0.6252, 0.2467],
        [0.7231, 0.9338, 0.1279, 0.0808]])

In [18]:
print(f"Random Tensor shape {random_tensor.shape} and Random Tensor dimension is {random_tensor.ndim}")

Random Tensor shape torch.Size([3, 4]) and Random Tensor dimension is 2


In [19]:
#Create a random Tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
#Create all Zeros Tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create all Ones Tesnsor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Creating a range of Tensor and Tensor-like

In [22]:
# use torch.range()
one_to_ten = torch.arange(1,11)
# using step in arange
one_to_some_step = torch.arange(start = 1, end = 11, step = 1)
one_to_some_step


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#Create Tensor-like
ten_zeros = torch.zeros_like(input=one_to_some_step)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataType
#### **NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
     1.Tensor not right shape    
     2.Tensor not right dataType
     3.Tensor not on the right Device


In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 7.0], 
                               dtype=None, # what data type is the tensor (e.g. float32 and float 16)
                               device=None,# what device  is your tensor on
                               requires_grad=False) # Wheather or not to track gradient with this tensors operation
float_32_tensor

tensor([3., 6., 7.])

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 7.], dtype=torch.float16)

In [26]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 49.])

In [27]:
# Create some Tensor 

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9616, 0.2553, 0.1501, 0.6616],
        [0.3390, 0.2590, 0.7703, 0.6717],
        [0.6129, 0.9843, 0.8939, 0.4309]])

In [28]:
# Find Out Detalis about Some_Tensor 
print(f"Datatype of Tensor is {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

Datatype of Tensor is torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on cpu


### Manipulating the Tensor (Tensor operation)


In [29]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [30]:
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
# Manipulating using Functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [31]:
#Element wise Multiplication
print(tensor,"*",tensor)
print(f"Equal to: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal to: tensor([1, 4, 9])


In [32]:
%%time
# Matrix Multiplication 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [33]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 1 ms


In [34]:
print(torch.matmul(torch.rand(3,2), (torch.rand(3,2)).T))
torch.mm(torch.rand(2,3), (torch.rand(2,3)).T) # torch.mm is same as torch.matmul (it's an alias for matmul)

tensor([[0.9329, 0.9139, 0.5525],
        [0.5492, 0.6393, 0.4502],
        [0.7800, 0.6464, 0.3167]])


tensor([[1.2007, 1.2435],
        [0.8240, 0.9757]])

#### Finding The min, Max, Mean,  Sum, Etc (tensor aggregation) 

In [35]:
x = torch.arange(start = 0, end= 100, step= 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
f"min :{x.min()} and {torch.min(x)}", f"max: {x.max()} and {torch.max(x)}"

('min :0 and 0', 'max: 90 and 90')

In [37]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors


In [39]:
# Create a Tensor 
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
# Add an extra dimension to x
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape, x_reshape.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [41]:
z = x.view(1,9)
z, z.shape, z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [42]:
#changing z changes x (because a view of a tensor shares the same memory as the original input tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [43]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked, x_stacked.shape, x_stacked.ndim  

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]),
 2)

In [44]:
# torch.squeeze() - removes all single dimensions from a target tensor 
print(f"Previous Tensor: {x_reshape}")
print(f"previous Tensor shape: {x_reshape.shape}")

# Remove Extra dimensions from x_reshape
x_squeeze = torch.squeeze(x_reshape)
print(f"After Squeeze: {x_squeeze}")
print(f"After Squeeze: {x_squeeze.shape if x_squeeze.ndim == 1 else 'not a 1D tensor'}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous Tensor shape: torch.Size([1, 9])
After Squeeze: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
After Squeeze: torch.Size([9])
